version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./docker/run/nginx/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - php
  php:
    build:
     context: .
     dockerfile: ./docker/run/php/Dockerfile
    volumes:
      - ./code:/var/www/

